apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment

#creates three identical pods. 
spec:
  replicas: 3

  selector:
    matchLabels:
      app: microservice

  template:
    metadata:
      labels:
        app: microservice

    #use the microservice image we built and pushed to Docker Hub.
    spec:
      containers:
        - name: microservice
          image: raw1218/k8s-microservice-pipeline:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000