apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-app-dev
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: k8s/overlays/dev
    repoURL: https://github.com/raw1218/aws-k8s-microservice-pipeline
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
