apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: microservice

  template:
    metadata:
      labels:
        app: microservice

    spec:
      containers:
        - name: microservice
          image: raw1218/k8s-microservice-pipeline:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_PORT

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD